### ISSUE TITLE
Building plugins?

### ISSUE THREAD

**Issue by altano** [caddyserver/caddy-docker#131]
I'm trying to follow the https://hub.docker.com/_/caddy/ docs "Adding custom Caddy modules" section. I have two plugins (www.github.com/lucaslorentz/caddy-docker-proxy and www.github.com/caddy-dns/lego-deprecated) that I'm trying to use. `caddy-docker-proxy` says:

> You can build caddy using xcaddy or caddy docker builder.
> Use module name github.com/lucaslorentz/caddy-docker-proxy/plugin/v2 to add this plugin to your build.

I'm having trouble doing this. I started with:

docker-compose.yaml:
```yaml
version: "3.7"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels: # Global options
      ...

  # Proxy to container
  whoami0:
    image: jwilder/whoami
    labels:
      caddy: whoami-internal.mydomain.com
      caddy.reverse_proxy: "{{upstreams 8000}}"
      caddy.tls: "internal"
```

Works great. If I try to add in the lego plugin, though, I just get default caddy and this plugin stops working:

./docker-compose.yaml:
```yaml
version: "3.7"
services:
  caddy:
    # use a custom build instead
    # image: lucaslorentz/caddy-docker-proxy:ci-alpine
    build: ./custom-caddy-build
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels: # Global options
      ...

  # Proxy to container
  whoami0:
    image: jwilder/whoami
    networks:
      - docker_web
    labels:
      caddy: whoami-internal.mydomain.com
      caddy.reverse_proxy: "{{upstreams 8000}}"
      caddy.tls: "internal"
```

./custom-caddy-build/Dockerfile:
```docker
FROM caddy:2-builder-alpine AS builder

RUN xcaddy build \
  --with github.com/lucaslorentz/caddy-docker-proxy/plugin/v2 \
  --with github.com/caddy-dns/lego-deprecated

FROM caddy:2-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

But this just gives me a stock Caddyfile. Could we get a fleshed-out example for how to use xcaddy with plugins? @hairyhenderson? I'm posting here since this isn't caddy-docker-proxy specific and is just a generic "how do I build plugins" question.
