### ISSUE TITLE
443: bind: permission denied

### ISSUE THREAD

**Issue by lemos1235** [caddyserver/caddy-docker#21]
I had a docker-compose file as below: 
```
 caddy:
    image: caddy/caddy:alpine
    #restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    environment:
      - ACME_AGREE=true
```

but got the error log:
loading initial config: loading new config: http app module: start: tcp: listening on :443: listen tcp :443: bind: permission denied
