### ISSUE TITLE
Can't run Caddy V2. Any example?

### ISSUE THREAD

**Issue by pascalandy** [caddyserver/caddy-docker#22]
Hi,

I run Caddy v1.0.3 in prod as a basic web server for a while now. 
But I wasn't able to run V2. Any example to share?

### compose-caddy.yml

Here is my present setup:

```
version: "3.3"

services:

  caddy:
    image: abiosoft/caddy:1.0.3-no-stats
    container_name: caddy
    hostname: caddy
    restart: unless-stopped
    volumes:
      - /mnt/webapps/blue:/srv

    labels:
      #### core configs
      - "traefik.enable=true"
      # - "traefik.http.routers.caddy.service=caddy" # swarm
      - "traefik.http.routers.caddy.rule=Host(`devkiwi.club`) && PathPrefix(`/caddy`)"
      - "traefik.http.services.caddy.loadbalancer.server.port=2015"
      #### set TLS (https)
      - "traefik.http.routers.caddy.entrypoints=websecure"
      - "traefik.http.routers.caddy.tls=true"
      - "traefik.http.routers.caddy.tls.certresolver=leresolver"
      #### Apply rules (middlewares)
      - "traefik.http.routers.caddy.middlewares=RuleGrpMain"

      #### https://twitter.com/askpascalandy
```
