### ISSUE TITLE
Special characters handled incorrectly when using with Docker Compose

### ISSUE THREAD

**Issue by Klooven** [caddyserver/caddy-docker#237]
I'm running the following simple configuration:

### `compose.yml`

```yaml
services:
  proxy:
    image: caddy:2.5.0-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - proxy:/data
      - ./Caddyfile:/etc/caddy/Caddyfile

volumes:
  proxy:
```

### `Caddyfile`

```
special-chars.klooven.link {
  respond "ääkkösiä"
}
```

### Environment

```
> docker -v
Docker version 20.10.14, build a224086
> docker compose version
Docker Compose version v2.3.3
```

The host is running Ubuntu 22.04 LTS

---

Everything works as expected until this, but when I visit the address I've configured in the Caddyfile, I get the following result:

<img width="408" alt="image" src="https://user-images.githubusercontent.com/12278148/165802996-8479bc13-c97f-408e-ba55-2d0787cfda28.png">

The result I'm expecting to see is obviously:

```
ääkkösiä
```

I haven't encountered the issue when running Caddy "natively", but with my Docker Compose setups this has always been an issue. When using the `reverse_proxy` directive, however, all content served through Caddy render special characters correctly. The only place that seems to have an issue with them is the Caddyfile.

---

I have yet to determine if this issue originates from the Caddy Docker images or some other part in the process (e.g. the Alpine base image etc.), but I thought that this could be a good place to ask first. I'm happy to share more details if needed, and continue will debugging if anyone has an idea how to resolve the issue.
