### ISSUE TITLE
Caddyfile: permission denied

### ISSUE THREAD

**Issue by ShockedCoder** [caddyserver/caddy-docker#262]
It cannot read the Caddyfile even though its permissions are 0644 and it still can't read it even when the perms are 0777.
I've tried everything that I could think of, but I can't find any other instance of this happening.
And I've tried it with the default `docker-compose.yml` and that also didn't work.

Some more info in-case it's needed:

`docker-compose.yml`:
```yml
version: '3.3'
networks:
  caddy:
services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - ./caddy_data:/data
      - ./caddy_config:/config
    networks:
      - caddy
volumes:
  caddy_data:
    external: true
  caddy_config:
```

![Caddyfile permission denied](https://user-images.githubusercontent.com/40272709/191501363-015ffa4f-bff0-4802-91d6-dfefa3cc6b78.png)
