### ISSUE TITLE
Caddy generating bunches of ssl_client zombie processes

### ISSUE THREAD

**Issue by joshavant** [caddyserver/caddy-docker#276]
After launching a Caddy deployment that's exposed to the public internet, it seems that Caddy is leaving failed `ssl_client` processes open and not cleaning them up.

When I run `ps -ax` on my Docker Host, I see thousands of these:
```
  73220 ?        Z      0:00 [ssl_client] <defunct>
  73240 ?        Z      0:00 [ssl_client] <defunct>
  73257 ?        Z      0:00 [ssl_client] <defunct>
  73276 ?        Z      0:00 [ssl_client] <defunct>
  73294 ?        Z      0:00 [ssl_client] <defunct>
  73312 ?        Z      0:00 [ssl_client] <defunct>
  73330 ?        Z      0:00 [ssl_client] <defunct>
  73350 ?        Z      0:00 [ssl_client] <defunct>
  73368 ?        Z      0:00 [ssl_client] <defunct>
  73388 ?        Z      0:00 [ssl_client] <defunct>
  73409 ?        Z      0:00 [ssl_client] <defunct>
  73425 ?        Z      0:00 [ssl_client] <defunct>
  73442 ?        Z      0:00 [ssl_client] <defunct>
  73461 ?        Z      0:00 [ssl_client] <defunct>
  73477 ?        Z      0:00 [ssl_client] <defunct>
  73495 ?        Z      0:00 [ssl_client] <defunct>
  73513 ?        Z      0:00 [ssl_client] <defunct>
```

When I check what the parent process of all of these, it's Caddy:
```
ubuntu@server:~$ cat /proc/73220/status | grep PPid
PPid:	1371
ubuntu@server:~$ cat /proc/1371/status
Name:	caddy
```

As well, my motd tells me on SSH login that:
`=> There are 3821 zombie processes.`

These thousands of zombie processes are causing my host server to use lots of memory and, eventually, grind to a halt, requiring a restart.

**System + Version Information**
- Caddy 2.6.2 Docker Hub image 
- Docker Compose
- Ubuntu Server 20.04

Relevant `docker-compose.yml` section:

```
services:
  caddy:
    image: caddy:2.6.2
    restart: always
    environment:
      - INTERNET_HOST
      - DOCKER_HOST
      - DOCKER_PORT
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost/caddy-health-check" ]
      interval: 10s
      timeout: 5s
      retries: 5
```

`Caddyfile`

```
{$INTERNET_HOST} {
	reverse_proxy {$DOCKER_HOST}:{$DOCKER_PORT}
	respond /caddy-health-check 200
}
```

Any thoughts how I could stop this?
