### ISSUE TITLE
rootless HTTPs not working due to missing /data and /config permissions 

### ISSUE THREAD

**Issue by codeInTheShell** [caddyserver/caddy-docker#287]
A documentation type deployment of caddy which runs as root with docker-compose (https://hub.docker.com/_/caddy) works with auto-ssl flawlessly. 
If a docker deployment has the flag user set to 1000:1000 and a named volume is used instead of a local path the user permissions stay root. If a deployment has just user set to 1000:1000 but still uses local paths, the created directories will still have root permissions.

The only solution is to manually chown -R 1000:1000 either the docker volume _data/ directory or the local path. 

Sample docker-compose.yaml
```
version: "3.9"                                                                                                                                                                                                     
services:                                                                                                
  caddy:                                                                                                                                                                               
    image: caddy:2-alpine                                                                               
    restart: unless-stopped                                                                              
    user: 1000:1000     # <--- the culprit                                                                                 
    ports:                                                                                              
      - "80:80"                                                                                         
      - "443:443"                                                                                       
      - "443:443/udp"                                                                                   
    volumes:                                                                                             
      - $PWD/../Caddyfile:/etc/caddy/Caddyfile                                                           
      - $PWD/site:/srv                                                                                   v
      - caddy_data:/data                                                                                 
      - caddy_config:/config            
      - ./caddy_data:/data                                                                                 
      - ./caddy_config:/config                                                                             
                                                                                                         
volumes:                                                                                                 
  caddy_data:                                                                                            
  caddy_config:
```

Unfortunately the below Dockerfile didn't help either.

```
ENV UID 1000
ENV GID 1000

RUN addgroup -g $GID -S caddy ; adduser -SDHs /sbin/nologin -u $UID -G caddy caddy  ; chown $UID:$GID /data ; chown $UID:$GID /config
VOLUME /data
VOLUME /config
RUN chown -R $UID:$GID /data /config
```

The result is the same either way unless i manually chown -R it with the respective  user and group id:

```
{"level":"error","ts":1680045963.1747446,"logger":"tls","msg":"job failed","error":"domain.tld: obtaining certificate: failed storage check: open /data/caddy/rw_test_4836700798867844449: permission denied - storage is probably misconfigured"}
{"level":"error","ts":1680045963.1751785,"logger":"tls","msg":"job failed","error":"domain.tld: obtaining certificate: failed storage check: open /data/caddy/rw_test_148537797091318011: permission denied - storage is probably misconfigured"}
{"level":"error","ts":1680045963.1753407,"msg":"unable to autosave config","file":"/config/caddy/autosave.json","error":"open /config/caddy/autosave.json: permission denied"}
{"level":"info","ts":1680045963.1753864,"msg":"serving initial configuration"}
```

**Comment by francislavoie** [comment]
Hey @tianon I hope you don't mind the ping, could you give us some pointers here?

I'm not sure what the correct way to handle volumes that need write access as non-root, for official images. I didn't see any guidance about that in the https://github.com/docker-library/official-images README other than a mention of `gosu` but I'm not sure how that interacts with volumes or if it helps with that at all 🤔

**Comment by paulo-erichsen** [comment]
I had the same issue. My understanding is that the Dockerfile calls `mkdir -p` on some folders, but they seem to be created as root??

https://github.com/caddyserver/caddy-docker/blob/bee0fa4b04c8f268e7e9ae12c73225772f22d38c/Dockerfile.tmpl#L9-L13

I use ansible to configure caddy and my workaround was to create all the folders that caddy uses beforehand. (I had to `rm -r` the older folders)

```
---
- name: Create caddy config directory
  ansible.builtin.file:
    path: "{{ project_directory }}/caddy/{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ user_id }}"
    group: "{{ group_id }}"
  loop:
    - config
    - data
    - etc
    - etc/caddy
    - logs
```

NOTE: one interesting thing is that the logs folder isn't created in that `mkdir` that I've referenced. That must be happening somewhere else maybe after caddy starts?

**Comment by dimkasta** [comment]
A bit late, but I hope this helps. 

@tianon Content, ownership and permissions can be defined in volumes using Dockerfile only before they are created. You can use things like COPY and/with chmod/chown and the image that creates the volume will populate it with its definitions.

@codeInTheShell For arbitrary accounts in existing volumes, you can try setting it first to root like 0:0, then exec into the container to do any chown that you need, and then switch to the new IDs. A temp root bastion container could be handy for that. Or an entrypoint script that calls a separate startup script and/or does not start the service if the user is root, but keeps the container running

**Comment by tcurdt** [comment]
This situation is a little unfortunate. I blame docker for not allowing specifying ownership for volumes. 😒

While still not ideal, the most simple workaround seems to be to add one more layer and pass in the `UID` and `GID`. At least it seems to work fine for me.

```
FROM caddy:2.7-alpine

ENV UID 65534
ENV GID 65534
RUN chown -R $UID:$GID /data /config
```

**Comment by laglink17** [comment]
> This situation is a little unfortunate. I blame docker for not allowing specifying ownership for volumes. 😒
> 
> While still not ideal, the most simple workaround seems to be to add one more layer and pass in the `UID` and `GID`. At least it seems to work fine for me.
> 
> ```
> FROM caddy:2.7-alpine
> 
> ENV UID 65534
> ENV GID 65534
> RUN chown -R $UID:$GID /data /config
> ```

This actually did not work for me. Even after adding the UID/GID and changing ownership, the folders and everything inside is changed back to root after running the container.

The solution, in my case, was to modify the Dockerfile from scratch. Using the alpine Dockerfile and there, adding the code for UID and GID variables, and modifying the owner of the workdir.

```
FROM alpine:3.21

# Set environment variables for UID and GID
ENV USER_UID=1001
ENV USER_GID=1001

# Create a non-root user based on the UID and GID environment variables
RUN addgroup -g $USER_GID appgroup && \
    adduser -D -u $USER_UID -G appgroup appuser

# Set the ownership of /srv directory to the non-root user
RUN chown -R appuser:appgroup /srv

...
```

**Comment by tcurdt** [comment]
> This actually did not work for me. Even after adding the UID/GID and changing ownership, the folders and everything inside is changed back to root after running the container.

Well, you obviously need to match the UID/GID with the user you are running the container as.

```
  caddy:
    container_name: caddy
    image: caddy:2.10-alpine
    read_only: true
    user: 65534:65534
```
