### ISSUE TITLE
healthcheck always shows unhealthy

### ISSUE THREAD

**Issue by n2aod** [caddyserver/caddy-docker#331]
I configure healthcheck like this in dockercompose, but docker keeps showing that the caddy container is in an unhealthy state. How should I modify it?
```
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:2019/metrics", "||", "exit", "1"]
      start_period: 60s
      interval: 10s
      timeout: 5s
      retries: 3
```
