### ISSUE TITLE
Custom image builds correctly but not running in compose

### ISSUE THREAD

**Issue by ctrenthem159** [caddyserver/caddy-docker#390]
I raised an issue in the caddy-dns/cloudfare project due to a problem with the module not loading properly. After investigating further, I found that the module is being added to caddy correctly, but for some reason when running the image through docker compose, it will not read the correct binary. The issue there is https://github.com/caddy-dns/cloudflare/issues/95

 I also verified that the image is building correctly by running the image independently from the compose.yaml file and running `caddy list-modules` which does show the module is being loaded by the caddy binary. I don't understand why the binary has the module but still fails to run in the container. I made sure the /config and /data volumes were removed before running the last few tests, so it's not a problem with artifacts in those folders.

## Docker versions
```
$ docker version

Client: Docker Engine - Community
 Version:           27.5.1
 API version:       1.47
 Go version:        go1.22.11
 Git commit:        9f9e405
 Built:             Wed Jan 22 13:41:48 2025
 OS/Arch:           linux/amd64
 Context:           default

$ docker compose version

Docker Compose version v2.32.4
```

## compose.yaml
```
    caddy:
        build:
            dockerfile: ./caddy.Dockerfile
        container_name: caddy
        restart: unless-stopped
        cap_add: ["NET_ADMIN"]
        ports: ["80:80", "443:443", "443:443/udp"]
        environment:
            - DOMAIN={REDACTED}
        volumes:
            - $PWD/conf:/etc/caddy
            - caddy_data:/data
            - caddy_config:/config
        networks: ["frontend"]
```

## caddy.Dockerfile
```
FROM caddy:2.9.1-builder AS builder

RUN xcaddy build \
    --with github.com/caddy-dns/cloudflare

FROM caddy:2.9.1
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

## Caddyfile
```
{
	servers {
		trusted_proxies static 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16 fc00::/7
	}
	acme_dns cloudfare {$HARDCODED_API_KEY}
}
```

Everything goes fine, then run `$ docker log caddy -f` and get an infinite restart loop with this output.
```
{"level":"info","ts":1740339167.9436042,"msg":"using config from file","file":"/etc/caddy/Caddyfile"}
Error: adapting config using caddyfile: parsing caddyfile tokens for 'acme_dns': getting module named 'dns.providers.cloudfare': module not registered: dns.providers.cloudfare, at /etc/caddy/Caddyfile:5
{"level":"info","ts":1740339171.3738594,"msg":"using config from file","file":"/etc/caddy/Caddyfile"}
Error: adapting config using caddyfile: parsing caddyfile tokens for 'acme_dns': getting module named 'dns.providers.cloudfare': module not registered: dns.providers.cloudfare, at /etc/caddy/Caddyfile:5
```

## docker exec TEST_CONTAINER caddy list-modules
```
<SNIP>
tls.leaf_cert_loader.storage
tls.permission.http
tls.stek.distributed
tls.stek.standard

  Standard modules: 124

dns.providers.cloudflare

  Non-standard modules: 1

  Unknown modules: 0
```
